### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by QJYJH** [HaotianZhangAI4Science/SurfGen#6]
为什么我使用了你提供的surfgen的yml环境，运行“python gen.py --outdir example --check_point ./ckpt/val_119.pt --ply_file ./example/3cl_pocket_8.0_res_1.5.ply”这个命令时报错：Traceback (most recent call last):
  File "gen.py", line 12, in <module>
    from utils.transforms import *
  File "/home/data1/XRJ/SurfGen-main/utils/transforms.py", line 14, in <module>
    from torch_geometric.nn.pool import knn_graph
  File "/home/data1/anaconda3/envs/geobind/lib/python3.7/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/data1/anaconda3/envs/geobind/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/data1/anaconda3/envs/geobind/lib/python3.7/site-packages/torch_geometric/data/data.py", line 9, in <module>
    from torch_sparse import SparseTensor
ModuleNotFoundError: No module named 'torch_sparse'

**Comment by HaotianZhangAI4Science** [comment]
Dear Sir, the error suggests that you lack the torch_sparse, which may imply that your PyG suite is not successfully installed. My environment is built upon the CUDA 11.3, please manually config your environment according to your own CUDA version.

**Comment by QJYJH** [comment]
> 尊敬的先生，该错误表明您缺少torch_sparse，这可能意味着您的 PyG 套件未成功安装。我的环境是基于 CUDA 11.3 构建的，请根据您自己的 CUDA 版本手动配置您的环境。

Thank you so much for your reply, it solved the problem for me.I managed to generate some small s of "3cl".I noticed that you used an "in situ estimation of binding energy—scoring energy" method in your validation experiments, can you specify how this was accomplished?

**Comment by HaotianZhangAI4Science** [comment]
Dear Sir, I have summarized the scripts at the https://github.com/HaotianZhangAI4Science/AI-Physics-DrugDiscovery/blob/main/pydocking/docking/qvina.py, the function scoring_with_qvina02 is exactly what you want.
